### ISSUE TITLE
crash in basic example

### ISSUE THREAD

**Issue by davidpanderson** [cuthbertLab/music21#1172]
music21 version: 7.1.0
python version: 3.9.7
OS: Win10

The "getting started" example crashes:

>>> n = note.Note("D#3")
>>> n.duration.type = 'half'
>>> n.show()
Traceback (most recent call last):
  File "<pyshell#9>", line 1, in <module>
    n.show()
  File "C:\Users\davea\AppData\Local\Programs\Python\Python39\lib\site-packages\music21\base.py", line 2738, in show
    return formatWriter.show(self,
  File "C:\Users\davea\AppData\Local\Programs\Python\Python39\lib\site-packages\music21\converter\subConverters.py", line 1097, in show
    self.launch(returnedFilePath, fmt=fmt, app=app)
  File "C:\Users\davea\AppData\Local\Programs\Python\Python39\lib\site-packages\music21\converter\subConverters.py", line 196, in launch
    subprocess.run(cmd, check=False, shell=shell)
  File "C:\Users\davea\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\davea\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\davea\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by mscuthbert** [comment]
Did you run the configuration tool before starting?

**Comment by davidpanderson** [comment]
That was indeed the problem.  You might want to mention configure.run() in the "What is Music21?" page, and maybe do a runtime check.

**Comment by mscuthbert** [comment]
If it's not in the Installing Music21 page, please make an issue.
