### ISSUE TITLE
MEI transposition information of instruments not parsed

### ISSUE THREAD

**Issue by sonovice** [cuthbertLab/music21#125]
It seems like the transposition information of instruments in an MEI file are not parsed.
Trying to get the actual sounding pitch of the notes always results in `music21.exceptions21.StreamException: atSoundingPitch is unknown: cannot transpose`

The MEI file does include the transpositions in a correct manner, for example `trans.semi="-7"`.

Minimal example:
```python
stream = converter.parseFile('Hummel_Concerto_for_trumpet.mei', None, "mei", True)
stream.toSoundingPitch(inPlace=True)
```

The MEI file used: [Hummel Concerto](http://www.verovio.org/examples/downloads/Hummel_Concerto_for_trumpet.mei)

**Comment by crantila** [comment]
Thanks for this report, @sonovice. It looks like music21 isn't pulling in any of the instrument information in that file. I'm investigating as we speak!

**Comment by crantila** [comment]
After some investigation, I can reproduce the issue on the master branch, and on the branch in pull request #126.

As for finding the problem, ``music21.mei.base.staffGrpFromElement()`` appears to return ``Instrument`` objects as expected, so the problem must be at a higher level in the score hierarchy, or a later point in processing. I can also reproduce the issue with a modified version of the built-in "test_file.mei" that adds a ``@label`` attribute to the ``<staffDef>`` and should therefore produce a named ``Instrument``.

I know this used to work, so the next step is a git bisection to find the commit that broke things.

**Comment by mscuthbert** [comment]
I know our transposition routines but I don't know the MEI code well at all.  Ping me if I can help.

**Comment by sonovice** [comment]
Any progress on this? Sorry for bumping randomly... If i can help in any way, please let me know.

**Comment by crantila** [comment]
No progress, but you can help by fixing it. :smile: 

I'll take a look today. This isn't a high priority for me at the moment, so I will forget about it. Therefore please do ask periodically if there's no activity on this issue!

**Comment by crantila** [comment]
Okay, in today's episode, I determined that instrument data was never properly imported. I really thought it was too.

**Comment by sonovice** [comment]
Periodical bump ;-)

**Comment by crantila** [comment]
I added a test in that there commit 0664941. I also used the small MEI document in that test to find the problem.

Currently, the MEI importer puts Instrument objects in Measure objects, like this:
```
>>> zed.parts[0]
<music21.stream.Part 0x7f10731b2710>
>>> zed.parts[0].show('text')
{0.0} <music21.stream.Measure 1 offset=0.0>
    {0.0} <music21.instrument.Instrument 1: Clarinet: Clarinet>
    {0.0} <music21.clef.BassClef>
    {0.0} <music21.key.KeySignature of 1 flat, mode major>
    {0.0} <music21.meter.TimeSignature 8/8>
    {0.0} <music21.stream.Voice 1>
        {0.0} <music21.note.Note E>
```

It was probably through an inspection like this that I initially determined that instrument metadata is imported properly&mdash;you can see it right there!

However, I took a quick look in `Stream.getInstruments()` and discovered that it only looks one level deep for Instrument objects. Therefore the solution is to place the Instrument at the same level as the Measure, rather than inside.

**Comment by mscuthbert** [comment]
It's possible that `Stream.getInstruments()` should look deeper, especially since recursive searches are now (in v.3) as easy to do as non-recursive. Would you prefer that?

**Comment by crantila** [comment]
It would be easier for me, but is it the right approach? My inclination is that all the *-to-music21 converters should do things as similarly as possible. Otherwise what's the point in converting them to "the same" music21 format?

**Comment by mscuthbert** [comment]
It wouldn't be a change in the conversion process per se, since only the MEI process uses .getInstruments() in the converting.  It'd be a change in what "getInstruments()" means.  If it only looks at the current stream itself, then there could be good reasons not to change.  But if it looks at one layer down then it should look at all layers down.  

In any case, it seems like "getInstruments()" should be something that could work on a StreamIterator instead of a Stream anyhow, in which case, "s.recurse().getInstruments()" should work.

**Comment by crantila** [comment]
The only place I'm using `getInstruments()` is the test file, not in the actual conversion. I foolishly assumed that, if `getInstruments()` returns an Instrument object with the correct attributes, the transposition problem would be fixed. Not true.

So I'll get this bit screwed down with the Instrument placement. It sounds like `getInstruments()` should do a recursive search either way.

The saga continues. Sorry, @sonovice !

**Comment by crantila** [comment]
Actually this one was easy. We need to set ``atSoundingPitch`` on imported Part objects. Thankfully:
> As a basic principle, MEI always captures written pitches
([source](http://music-encoding.org/documentation/2.1.1/cmn/))

So it's safe to assume that ``atSoundingPitch`` is always ``False`` during conversion.

Pull request to follow in a few moments.

**Comment by mscuthbert** [comment]
Oh, getInstruments() is a mess -- it goes one level UP! not down in its search, which is something we don't do anymore except as "getContextByClass()".  My guess is that it'll need to be rewritten from scratch or removed.  To do what we talked about is simply: s.recurse().getElementsByClass('Instrument')

**Comment by crantila** [comment]
Thanks Myke, sounds like you have your work cut out for you in `getInstruments()`!

And thanks to @sonovice for reporting the issue, and for your patience.

**Comment by sonovice** [comment]
Thanks to YOU for the great support! :-)

**Comment by sonovice** [comment]
Hmm, I still get an error on some files:

```python
Traceback (most recent call last):
  File "C:/Users/Simon/Dropbox/Dissertation/Code/tests/mei2wave.py", line 17, in <module>
    stream.toSoundingPitch(inPlace=True)
  File "C:\Python34\lib\site-packages\music21-3.0.2-py3.4.egg\music21\stream\__init__.py", line 4062, in toSoundingPitch
    p.toSoundingPitch(inPlace=True)
  File "C:\Python34\lib\site-packages\music21-3.0.2-py3.4.egg\music21\stream\__init__.py", line 4069, in toSoundingPitch
    returnObj._transposeByInstrument(reverse=False, inPlace=True)
  File "C:\Python34\lib\site-packages\music21-3.0.2-py3.4.egg\music21\stream\__init__.py", line 4009, in _transposeByInstrument
    inPlace=True)
  File "C:\Python34\lib\site-packages\music21-3.0.2-py3.4.egg\music21\stream\__init__.py", line 5985, in extendDurationAndGetBoundaries
    raise StreamException('no elements of this class defined in this Stream')
music21.exceptions21.StreamException: no elements of this class defined in this Stream
```

Code:
```python
stream = converter.parseFile('A_mov6_6.mei', None, "mei", True)
stream.toSoundingPitch(inPlace=True)
```

File: https://www.dropbox.com/s/rdvwjg3hv7kcj5p/A_mov6_6.mei?dl=1

**Comment by crantila** [comment]
Since this is a different (if admittedly related) bug, let's use issue #140. Thanks!
