### ISSUE TITLE
7.3 release is broken on PyPi

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#1259]
There is a `breakpoint()` in line 66 of setup.py

this means `pip install music21==7.3.0` fails with:

```shell
% py -m pip install music21==7.3.0      
Collecting music21==7.3.0
  Using cached music21-7.3.0.tar.gz (19.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      > /private/var/folders/_c/qsz9054d71v9z4wt9p38wc9c0000gn/T/pip-install-085wu6e9/music21_7ba89a0d31c64770a0392e05b7feacf6/setup.py(67)<module>()
      -> setuptools.setup(
      (Pdb) Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/_c/qsz9054d71v9z4wt9p38wc9c0000gn/T/pip-install-085wu6e9/music21_7ba89a0d31c64770a0392e05b7feacf6/setup.py", line 67, in <module>
          setuptools.setup(
        File "/private/var/folders/_c/qsz9054d71v9z4wt9p38wc9c0000gn/T/pip-install-085wu6e9/music21_7ba89a0d31c64770a0392e05b7feacf6/setup.py", line 67, in <module>
          setuptools.setup(
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/bdb.py", line 90, in trace_dispatch
          return self.dispatch_line(frame)
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/bdb.py", line 115, in dispatch_line
          if self.quitting: raise BdbQuit
      bdb.BdbQuit
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by arosen93** [comment]
I can also confirm it's broken. Reverting to the prior version resolves the issue.

**Comment by AlirezaM1999** [comment]
I had the same issue. best solution is to use **music21==7.1.0** for the time being
