### ISSUE TITLE
No support for entities defined in MusicXML `.dtd`

### ISSUE THREAD

**Issue by Alperencode** [cuthbertLab/music21#1370]
**music21 version**
?

**Problem summary**

conventer.parse() is not working anymore. I'm using the same script that I used before but it is not working anymore.

**Steps to reproduce**

```
from music21 import * 
import os

c = converter.parse('example.xml')
bu = braille.translate.objectToBraille(c)
ba = braille.basic.brailleUnicodeToBrailleAscii(bu)
print(ba)
```

**Expected vs. actual behavior**

When I was using this command before:
```
python .\converter.py > example.brf
```
It was successfully giving me the brf output but lately its causing this error:
```
Traceback (most recent call last):
  File ".\converter.py", line 4, in <module>
    c = converter.parse('example.xml')
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\site-packages\music21\converter\__init__.py", line 1168, in parse
    return parseFile(valueStr, number=number, format=m21Format,
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\site-packages\music21\converter\__init__.py", line 1037, in parseFile
    v.parseFile(fp, number=number, format=format, forceSource=forceSource, **keywords)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\site-packages\music21\converter\__init__.py", line 571, in parseFile
    self.parseFileNoPickle(fp, number, format, forceSource, **keywords)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\site-packages\music21\converter\__init__.py", line 504, in parseFileNoPickle
    self.subConverter.parseFile(fp, number=number, **keywords)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\site-packages\music21\converter\subConverters.py", line 910, in parseFile
    c.readFile(fp)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\site-packages\music21\musicxml\xmlToM21.py", line 852, in readFile
    etree = ET.parse(filename)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\xml\etree\ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\xml\etree\ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: undefined entity &auml;: line 44, column 33
 ```
I tried to download the older version of music21 like 6.0 versions but it's still giving the same error message. Is there anything changed about the converter or I'm making a mistake somewhere?

**Comment by jacobtylerwalls** [comment]
Hey @Alperencode sorry to hear you're having trouble.

If I'm understanding things right, `&auml;` is a [legal entity in the MusicXML spec](https://github.com/w3c/musicxml/blob/ed35369587262d0e128f447a1d40287f43b93dfc/schema/isolat1.ent#L55), but the XML parser from python's standard library that music21 depends on doesn't parse entities defined in external schema like that.

A long way of saying that `music21` probably won't support documents with such characters in the near future. (We'd need to use `lxml` instead as our XML parser.)

You could try replacing out those characters from your document before providing them to music21. A hassle, I know.

**Comment by Alperencode** [comment]
Thanks for the reply @jacobtylerwalls

You are right; it worked just fine when I removed the `&auml;`. I would love to look into your XML parser and see if there is any way to solve this issue in my free time. So is it okay to work on it, or as you said, there is no need to change it in the near time.

**Comment by jacobtylerwalls** [comment]
Glad it worked out. I figure the change to the parser (using `lxml` instead of `ElementTree`) would be significant enough that you'd want @mscuthbert to weigh in before putting time into it. It may be that we decide not to support those entities.

**Comment by Alperencode** [comment]
Yeah right and instead of bothering Mr. Michael and re-writing converter parser I can create a little script that cleans `&auml;` from XML files. Thanks for the help again @jacobtylerwalls!
