### ISSUE TITLE
ArticAttribs not correctly parsed from MEI file

### ISSUE THREAD

**Issue by sonovice** [cuthbertLab/music21#139]
Hallo again ;-)

I stumbled across an MEI file, that consistently crashes MEI although it's 100% valid according to the MEI2013 scheme:

File: https://www.dropbox.com/s/swv6bev6khsi4ki/A_mov6_7.mei?dl=1

```python
stream = converter.parseFile('A_mov6_7.mei', None, "mei", True)
```

returns:
```python
Traceback (most recent call last):
  File "C:/Users/Simon/Dropbox/Dissertation/Code/tests/mei2wave.py", line 12, in <module>
    stream = converter.parseFile(FILENAME, None, "mei", True)
  File "C:\Python34\lib\site-packages\music21-3.0.2-py3.4.egg\music21\converter\__init__.py", line 979, in parseFile
    v.parseFile(fp, number=number, format=format, forceSource=forceSource, **keywords)
  File "C:\Python34\lib\site-packages\music21-3.0.2-py3.4.egg\music21\converter\__init__.py", line 506, in parseFile
    self.parseFileNoPickle(fp, number, format, forceSource)
  File "C:\Python34\lib\site-packages\music21-3.0.2-py3.4.egg\music21\converter\__init__.py", line 443, in parseFileNoPickle
    self.subConverter.parseFile(fp, number=number)
  File "C:\Python34\lib\site-packages\music21-3.0.2-py3.4.egg\music21\converter\subConverters.py", line 1200, in parseFile
    self.parseData(dataStream, number)
  File "C:\Python34\lib\site-packages\music21-3.0.2-py3.4.egg\music21\converter\subConverters.py", line 1174, in parseData
    self.stream = mei.MeiToM21Converter(dataString).run()
  File "C:\Python34\lib\site-packages\music21-3.0.2-py3.4.egg\music21\mei\base.py", line 340, in run
    self.slurBundle)
  File "C:\Python34\lib\site-packages\music21-3.0.2-py3.4.egg\music21\mei\base.py", line 3409, in scoreFromElement
    parsed = sectionScoreCore(elem, allPartNs, slurBundle=slurBundle)[0]
  File "C:\Python34\lib\site-packages\music21-3.0.2-py3.4.egg\music21\mei\base.py", line 3259, in sectionScoreCore
    slurBundle=slurBundle)
  File "C:\Python34\lib\site-packages\music21-3.0.2-py3.4.egg\music21\mei\base.py", line 3359, in sectionFromElement
    backupMeasureNum=backupMeasureNum)
  File "C:\Python34\lib\site-packages\music21-3.0.2-py3.4.egg\music21\mei\base.py", line 3209, in sectionScoreCore
    activeMeter=activeMeter)
  File "C:\Python34\lib\site-packages\music21-3.0.2-py3.4.egg\music21\mei\base.py", line 3069, in measureFromElement
    slurBundle=slurBundle),
  File "C:\Python34\lib\site-packages\music21-3.0.2-py3.4.egg\music21\mei\base.py", line 2911, in staffFromElement
    layers.append(layerFromElement(eachTag, currentNValue, slurBundle=slurBundle))
  File "C:\Python34\lib\site-packages\music21-3.0.2-py3.4.egg\music21\mei\base.py", line 2836, in layerFromElement
    theLayer = _processEmbeddedElements(elem.iterfind('*'), tagToFunction, elem.tag, slurBundle)
  File "C:\Python34\lib\site-packages\music21-3.0.2-py3.4.egg\music21\mei\base.py", line 976, in _processEmbeddedElements
    result = mapping[eachElem.tag](eachElem, slurBundle)
  File "C:\Python34\lib\site-packages\music21-3.0.2-py3.4.egg\music21\mei\base.py", line 2158, in noteFromElement
    theNote.articulations.extend(_makeArticList(elem.get('artic')))
  File "C:\Python34\lib\site-packages\music21-3.0.2-py3.4.egg\music21\mei\base.py", line 594, in _makeArticList
    articList.extend(_articulationFromAttr(eachArtic))
  File "C:\Python34\lib\site-packages\music21-3.0.2-py3.4.egg\music21\mei\base.py", line 584, in _articulationFromAttr
    return (_attrTranslator(attr, 'artic', _ARTIC_ATTR_DICT)(),)
TypeError: 'NoneType' object is not callable
```

When I remove all articulation attributes, music21 parses the file flawlessly.

**Comment by crantila** [comment]
Yep, looks like a bug! Thanks for the report.

**Comment by sonovice** [comment]
Active polling ;-)
