### ISSUE TITLE
Program fails when trying to parse an ABC string

### ISSUE THREAD

**Issue by maranedah** [cuthbertLab/music21#1483]
**music21 version**
`8.1.0` 

**Problem summary**

Program fails when trying to parse an ABC string present in Nottingham Database. 

The song is "Keel Row", found in the file `reelsH-L.abc` shared in the [Nottingham Dataset from MusPy](https://salu133445.github.io/muspy/_modules/muspy/datasets/nmd.html#NottinghamDatabase)

The ABC string with the issue is the following:
```
X: 52
T:Keel Row
% Nottingham Music Database
F: http://www.youtube.com/watch?v=FqLbV00kxAk
F: http://www.youtube.com/watch?v=4tFaznuXjPM
F: http://www.youtube.com/watch?v=kV5JbDJXwyM
% abc2midi does not place 3 repeats !?
S:via PR
R: Reel
M:4/4
L:1/4
K:G
(d/2c/2)|:"G"BG/2B/2 "Am"cA/2c/2|"G"BG/2B/2 "D7"A/2F/2D/2c/2|\
"G"BG/2B/2 "D7"cA/2c/2|[1,2 "G"B/2G/2"D7"A/2F/2 "G"G/2e/2d/2c/2:|[3 "G"B/2G/2"D7"A/2F/2 "G"Gd/2c/2||"G"B/2d/2d/2g/2 "C"ed/2c/2|
"G"BG/2B/2 "D7"A/2F/2D/2c/2|"G"B/2d/2d/2g/2 "C"ed/2c/2|"G"B/2G/2"D7"A/2F/2 "G"G/2e/2d/2c/2|
"G"B/2d/2d/2g/2 "C"ed/2c/2|"G"BG/2B/2 "D7"A/2F/2D/2c/2|\
"G"B/2d/2d/2g/2 "C"f/2e/2d/2c/2|"G"B/2G/2"D7"A/2F/2 "G"G||
```

**Steps to reproduce**

1) Save the above ABC String as "test.abc"
2) On console call:
```
import music21

abc_str = open("test.abc", 'r').read()
data = music21.converter.parseData(abc_str)
```

**Expected vs. actual behavior**
Expected behaviour: A valid `music21.stream.Score` object.
Actual behavior: "ValueError: substring not found"

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\music21\converter\__init__.py", line 1167, in parseData
    v.parseData(dataStr, number=number, format=format, **keywords)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\music21\converter\__init__.py", line 698, in parseData
    self.subConverter.parseData(dataStr, number=number)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\music21\converter\subConverters.py", line 1244, in parseData
    abcHandler = af.readstr(strData, number=number)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\music21\abcFormat\__init__.py", line 3392, in readstr
    handler.process(strSrc)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\music21\abcFormat\__init__.py", line 2623, in process
    self.tokenProcess()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\music21\abcFormat\__init__.py", line 2618, in tokenProcess
    token.parse()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\music21\abcFormat\__init__.py", line 1692, in parse
    pos = nonChordSymStr.index(']')
ValueError: substring not found

**More information**
Tested on Windows. 

Also, I tried to verify if the issue was with the data, so I inputted the string into this online [ABC2MIDI Converter](https://www.mandolintab.net/abcconverter.php) and the page is able to parse it and return a valid MIDI file.

**Comment by mscuthbert** [comment]
music21 does not yet support 4.10 Variant Endings of https://abcnotation.com/wiki/abc:standard:v2.1 -- I've created a PR to at least make the error clearer, but I don't have time right now to make the rather major changes needed to support this, I'm afraid.
