### ISSUE TITLE
Raising a semitone and lowering an octave cannot coexist

### ISSUE THREAD

**Issue by Chunyuan-Li** [cuthbertLab/music21#1648]
**music21 version**

`9.1.0`   

**Problem summary**

Raising a semitone and lowering an octave cannot coexist

**Steps to reproduce**

```
s = music21.note.Note('C#-1')
```

**Expected vs. actual behavior**

```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/usr/local/lib/python3.10/dist-packages/music21/note.py", line 1543, in __init__
    self.pitch = Pitch(pitch, **keywords)
  File "/usr/local/lib/python3.10/dist-packages/music21/pitch.py", line 1953, in __init__
    self.name = name  # set based on string
  File "/usr/local/lib/python3.10/dist-packages/music21/pitch.py", line 2803, in name
    self.accidental = Accidental(usrStr[1:])
  File "/usr/local/lib/python3.10/dist-packages/music21/pitch.py", line 1010, in __init__
    self.set(specifier)
  File "/usr/local/lib/python3.10/dist-packages/music21/pitch.py", line 1274, in set
    raise AccidentalException(f'{name} is not a supported accidental type')
music21.pitch.AccidentalException: #- is not a supported accidental type
```
**More information**

**Comment by jacobtylerwalls** [comment]
Hi @Chunyuan-Li :wave:

The pitch constructors don't accept negative octave numbers, as they are interpreted as flats instead:
```py
>>> p = m21.pitch.Pitch('F0')
>>> p
<music21.pitch.Pitch F0>
>>> p.octave
0
>>> p = m21.pitch.Pitch('F-10')
>>> p.octave
10
>>> p.accidental
<music21.pitch.Accidental flat>
```

That means the exception you see here is expected.
