### ISSUE TITLE
ValueError while trying harmony.ChordSymbol with sus4, aug11, etc

### ISSUE THREAD

**Issue by Atorich** [cuthbertLab/music21#196]
subj.

```
Error
Traceback (most recent call last):
  File "/home/ator/PycharmProjects/chords/finder/tests/test_generator.py", line 42, in test_Adur7sus4
    ch = chords.get_chord_from_str('A7sus4')
  File "/home/ator/PycharmProjects/chords/finder/chords.py", line 26, in get_chord_from_str
    return harmony.ChordSymbol(value)
  File "/home/ator/venv/chords/local/lib/python2.7/site-packages/music21/harmony.py", line 1467, in __init__
    Harmony.__init__(self, figure, **keywords)
  File "/home/ator/venv/chords/local/lib/python2.7/site-packages/music21/harmony.py", line 192, in __init__
    self._parseFigure()
  File "/home/ator/venv/chords/local/lib/python2.7/site-packages/music21/harmony.py", line 1780, in _parseFigure
    if int(justints) > 20: # MSC: what is this doing?
ValueError: invalid literal for int() with base 10: '7sus4'
```

```
        for itemString in alterations:
            if itemString == '':
                continue
            justints = itemString.replace('b', '')
            justints = justints.replace('#', '')
            if int(justints) > 20: # MSC: what is this doing?
                skipNext = False
```

variable ```justints``` are 7sus4 and failing with ```int(justins)```

**Comment by mscuthbert** [comment]
See comments #197 first -- then we can reopen this if it still is a failure.
