### ISSUE TITLE
ChordStepModificationException for a seemingly valid MusicXML measure

### ISSUE THREAD

**Issue by p-himik** [cuthbertLab/music21#359]
Music21 5.5

Running
```python
from music21.musicxml.xmlToM21 import MeasureParser
from xml.etree.ElementTree import fromstring

measure = """\
<measure number="1">
   <attributes>
    <divisions>256</divisions>
    <key color="#000000">
     <fifths>0</fifths>
     <mode>major</mode>
    </key>
    <time color="#000000">
     <beats>4</beats>
     <beat-type>4</beat-type>
    </time>
    <staves>1</staves>
    <clef number="1" color="#000000">
     <sign>G</sign>
     <line>2</line>
    </clef>
    <staff-details number="1" print-object="yes" />
   </attributes>
   <harmony>
    <root>
     <root-step>E</root-step>
    </root>
    <kind>major-minor</kind>
    <degree>
     <degree-value>5</degree-value>
     <degree-alter>-1</degree-alter>
     <degree-type>alter</degree-type>
    </degree>
    <staff>1</staff>
   </harmony>
   <note>
       <rest measure="yes"/>
       <duration>256</duration>
   </note>
</measure>
"""

MeasureParser(fromstring(measure)).parse()
```
results in
```
Traceback (most recent call last):
  File "/home/p-himik/test.py", line 42, in <module>
    MeasureParser(fromstring(measure)).parse()
  File "/home/p-himik/dev/git/strayhorn/.venv/lib/python3.7/site-packages/music21/musicxml/xmlToM21.py", line 2317, in parse
    meth(mxObj)
  File "/home/p-himik/dev/git/strayhorn/.venv/lib/python3.7/site-packages/music21/musicxml/xmlToM21.py", line 4334, in xmlHarmony
    h = self.xmlToChordSymbol(mxHarmony)
  File "/home/p-himik/dev/git/strayhorn/.venv/lib/python3.7/site-packages/music21/musicxml/xmlToM21.py", line 4472, in xmlToChordSymbol
    cs._updatePitches()
  File "/home/p-himik/dev/git/strayhorn/.venv/lib/python3.7/site-packages/music21/harmony.py", line 1992, in _updatePitches
    pitches = list(self._adjustPitchesForChordStepModifications(pitches))
  File "/home/p-himik/dev/git/strayhorn/.venv/lib/python3.7/site-packages/music21/harmony.py", line 1717, in _adjustPitchesForChordStepModifications
    typeAlter(hD)
  File "/home/p-himik/dev/git/strayhorn/.venv/lib/python3.7/site-packages/music21/harmony.py", line 1707, in typeAlter
    'Degree not in specified chord: %s' % hD.degree)
music21.harmony.ChordStepModificationException: Degree not in specified chord: 5
```

I think the issue is in `harmony.py`: `CHORD_TYPES` has `minor-major-seventh` whereas `CHORD_ALIASES` specifies `major-minor-seventh` alias for `major-minor`.

**Comment by mscuthbert** [comment]
Thanks -- can you point to the musicxml spec page so I know which one to make canonical.  Thanks!

**Comment by p-himik** [comment]
In the description of the possible chord types,there's this section:
```
Sevenths:
	dominant (major triad, minor seventh)
	major-seventh (major triad, major seventh)
	minor-seventh (minor triad, minor seventh)
	diminished-seventh (diminished triad, diminished seventh)
	augmented-seventh (augmented triad, minor seventh)
	half-diminished (diminished triad, minor seventh)
	major-minor (minor triad, major seventh)
```

**Comment by mscuthbert** [comment]
Fixed!  Will be in the next release.
