### ISSUE TITLE
translate.midiFileToStream not working when iterating through large number of files

### ISSUE THREAD

**Issue by LucasLoerch** [cuthbertLab/music21#365]
I have data from an experiment where 75 participants performed 48 melodies each. I wrote a program based on music21 that analyses the performance of the participants. I already tested the program with a small number of files (5) and it worked without problems. When I want to run the program on all 3600 files, Python gives me the following error: "IndexError: list index out of range."
Below there is more information on code and errors. Unfortunately, I cannot give a reproducible example, as one would need the Midi files for that. (My system information: Windows 10 64bit, Python 3.7)
Thank you for your help and kind regards.

all 3600 Midi files are stored in the allData list
for eachFile in allData:
     eachFile=midi.translate.midiFileToStream(eachFile)

Traceback (most recent call last):

  File "<ipython-input-89-c811c87bafb5>", line 2, in <module>
    eachFile=m21.midi.translate.midiFileToStream(eachFile)

  File "C:\ProgramData\Anaconda3\lib\site-packages\music21\midi\translate.py", line 2115, in midiFileToStream
    **keywords)

  File "C:\ProgramData\Anaconda3\lib\site-packages\music21\midi\translate.py", line 1905, in midiTracksToStreams
    p = s.getElementsByClass('Stream')[0]

  File "C:\ProgramData\Anaconda3\lib\site-packages\music21\stream\iterator.py", line 328, in __getitem__
    e = fe[k]

IndexError: list index out of range

I also tried to use the converter.parse() function
for eachFile in allData:
     eachFile=converter.parse(dataPath+eachFile)
This gives me the same error:
Traceback (most recent call last):

  File "<ipython-input-95-f40d36bbe947>", line 2, in <module>
    eachFile=m21.converter.parse(performanceDataPath+eachFile)

  File "C:\ProgramData\Anaconda3\lib\site-packages\music21\converter\__init__.py", line 1127, in parse
    forceSource=forceSource, **keywords)

  File "C:\ProgramData\Anaconda3\lib\site-packages\music21\converter\__init__.py", line 1007, in parseFile
    v.parseFile(fp, number=number, format=format, forceSource=forceSource, **keywords)

  File "C:\ProgramData\Anaconda3\lib\site-packages\music21\converter\__init__.py", line 542, in parseFile
    self.parseFileNoPickle(fp, number, format, forceSource, **keywords)

  File "C:\ProgramData\Anaconda3\lib\site-packages\music21\converter\__init__.py", line 477, in parseFileNoPickle
    self.subConverter.parseFile(fp, number=number, **keywords)

  File "C:\ProgramData\Anaconda3\lib\site-packages\music21\converter\subConverters.py", line 982, in parseFile
    midiTranslate.midiFilePathToStream(fp, self.stream, **keywords)

  File "C:\ProgramData\Anaconda3\lib\site-packages\music21\midi\translate.py", line 1975, in midiFilePathToStream
    return midiFileToStream(mf, inputM21, **keywords)

  File "C:\ProgramData\Anaconda3\lib\site-packages\music21\midi\translate.py", line 2115, in midiFileToStream
    **keywords)

  File "C:\ProgramData\Anaconda3\lib\site-packages\music21\midi\translate.py", line 1905, in midiTracksToStreams
    p = s.getElementsByClass('Stream')[0]

  File "C:\ProgramData\Anaconda3\lib\site-packages\music21\stream\iterator.py", line 328, in __getitem__
    e = fe[k]

IndexError: list index out of range

**Comment by LucasLoerch** [comment]
Update: the program worked with 1000 files. It seems very strange to me why the iterator has a problem with 3600 files but works with 1000, which still is a large number of files. I am very happy for any suggestions on why this happens.

**Comment by LucasLoerch** [comment]
Update: Issue solved. The problem was caused by one file containing no notes. I narrowed the problem down to the empty file and deleted it, then it all worked without problems.
