### ISSUE TITLE
Import music21 throw an TypeError exception 

### ISSUE THREAD

**Issue by baites** [cuthbertLab/music21#494]
Here are the step to reproduce the issue. I am using python 3.8.0 and virtualenvwrapper to create a fresh virtual environment.

$ mkvirtualenv music21
(music21)$ pip list
pip        19.3.1 
setuptools 42.0.1 
wheel      0.33.6 
(music21)$ pip install music21
(music21)$ pip list
music21    5.7.1
pip        19.3.1
setuptools 42.0.1
wheel      0.33.6
(music21)$ python -c 'import music21'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/baites/.virtualenvs/music21/lib/python3.8/site-packages/music21/__init__.py", line 170, in <module>
    from music21 import base
  File "/home/baites/.virtualenvs/music21/lib/python3.8/site-packages/music21/base.py", line 94, in <module>
    from music21 import common
  File "/home/baites/.virtualenvs/music21/lib/python3.8/site-packages/music21/common/__init__.py", line 39, in <module>
    from music21.common.parallel import *
  File "/home/baites/.virtualenvs/music21/lib/python3.8/site-packages/music21/common/parallel.py", line 19, in <module>
    from music21.ext.joblib import Parallel, delayed  # @UnresolvedImport # type: ignore
  File "/home/baites/.virtualenvs/music21/lib/python3.8/site-packages/music21/ext/joblib/__init__.py", line 119, in <module>
    from .parallel import Parallel
  File "/home/baites/.virtualenvs/music21/lib/python3.8/site-packages/music21/ext/joblib/parallel.py", line 32, in <module>
    from .externals.cloudpickle import dumps, loads
  File "/home/baites/.virtualenvs/music21/lib/python3.8/site-packages/music21/ext/joblib/externals/cloudpickle/__init__.py", line 3, in <module>
    from .cloudpickle import *
  File "/home/baites/.virtualenvs/music21/lib/python3.8/site-packages/music21/ext/joblib/externals/cloudpickle/cloudpickle.py", line 167, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "/home/baites/.virtualenvs/music21/lib/python3.8/site-packages/music21/ext/joblib/externals/cloudpickle/cloudpickle.py", line 148, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)

**Comment by mscuthbert** [comment]
`music21` v5.X is not compatible with Python 3.8 and won't be.  v.6. will be released in alpha soon and supports Py3.8.

**Comment by baites** [comment]
Thanks Micheal, looking forward for v6 release. In any case, all the features I am using in music21 seems to work well using 5.5.0 release in Py3.8. So at the moment this is working as mitigation.

**Comment by baites** [comment]
I just finished testing using 5.7.2 and it worked out of the box!
