### ISSUE TITLE
Example code on homepage throws exception

### ISSUE THREAD

**Issue by lazzarello** [cuthbertLab/music21#517]
It appears #339 has regressed. I'm getting the same error from the code snipit on http://web.mit.edu/music21/
```python
catalog = stream.Opus()
for workName in corpus.chorales.Iterator():
  work = converter.parse(workName)
  firstTS = work.recurse().getElementsByClass('TimeSignature')[0]
  if firstTS.ratioString == '6/8':
    catalog.append(work.measures(0, 2))
catalog.show()
```

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/leeazzarello/src/practice-buddy/.venv/lib/python3.7/site-packages/music21/converter/__init__.py", line 1125, in parse
    elif not isinstance(value, bytes) and valueStr.startswith('MThd'):
AttributeError: 'Score' object has no attribute 'startswith'
```

**Comment by mscuthbert** [comment]
ah, yes, `corpus.chorales.Iterator()` produces Score objects, not strings now.

**Comment by mscuthbert** [comment]
Fixed.  Thanks!
