### ISSUE TITLE
Deepcopied GenericInterval object has no attribute '_value'

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#564]
You might be aware of this already, but if not, on master I see a test that errors out in interval.py running Python 3.7.7. I cannot reproduce this if I checkout commit `daad838`.

```
ERROR: testTransposeImported (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "interval.py", line 4145, in testTransposeImported
    sTransposed = sSub.flat.transpose('p5')
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/site-packages/music21/stream/__init__.py", line 7840, in transpose
    post = copy.deepcopy(self)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/site-packages/music21/stream/__init__.py", line 1498, in __deepcopy__
    new = self._deepcopySubclassable(memo)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/site-packages/music21/stream/__init__.py", line 1473, in _deepcopySubclassable
    newElement = copy.deepcopy(e, memo)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/site-packages/music21/base.py", line 588, in __deepcopy__
    new = self._deepcopySubclassable(memo)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/site-packages/music21/base.py", line 521, in _deepcopySubclassable
    deeplyCopiedObject = copy.deepcopy(attrValue, memo)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/site-packages/music21/base.py", line 588, in __deepcopy__
    new = self._deepcopySubclassable(memo)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/site-packages/music21/base.py", line 521, in _deepcopySubclassable
    deeplyCopiedObject = copy.deepcopy(attrValue, memo)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/copy.py", line 307, in _reconstruct
    value = deepcopy(value, memo)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/site-packages/music21/base.py", line 588, in __deepcopy__
    new = self._deepcopySubclassable(memo)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/site-packages/music21/base.py", line 521, in _deepcopySubclassable
    deeplyCopiedObject = copy.deepcopy(attrValue, memo)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/site-packages/music21/base.py", line 588, in __deepcopy__
    new = self._deepcopySubclassable(memo)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/site-packages/music21/base.py", line 521, in _deepcopySubclassable
    deeplyCopiedObject = copy.deepcopy(attrValue, memo)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/site-packages/music21/base.py", line 588, in __deepcopy__
    new = self._deepcopySubclassable(memo)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/site-packages/music21/base.py", line 518, in _deepcopySubclassable
    attrValue = getattr(self, name)
  File "/Users/jwalls/opt/anaconda3/envs/jtw_music21/lib/python3.7/site-packages/music21/interval.py", line 920, in value
    return self._value
AttributeError: 'GenericInterval' object has no attribute '_value'

----------------------------------------------------------------------
Ran 120 tests in 0.237s

FAILED (errors=1)
```

**Comment by jacobtylerwalls** [comment]
Gave this another shot and could not reproduce it. Must have been a bad episode of installing something haphazardly. This ticket apologizes for supplying a tale told by an idiot, signifying nothing!

**Comment by mscuthbert** [comment]
I think between 6 and 11 days ago is when I rewrote the whole backend infrastructure for Intervals so it's possible it got fixed then.  Thanks!
