### ISSUE TITLE
Overactive regex creates 'hordSymbolannotBeIdentified', which crashes later

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#615]
**music21 version**
`6.1`

**Problem summary**
Something having to do with 'chordSymbolCannotBeIdentified' and '/C' is causing `hordSymbolannotBeIdentified` to be passed to `int()` in `ChordSymbol._parseFigure()`

**Steps to reproduce**

```
c = chord.Chord(('A#', 'C', 'E'))
harmony.chordSymbolFromChord(c)
```

**Traceback**
  File "/Users/jwalls/music21/music21/harmony.py", line 1854, in _parseFigure
    justInts = int(justInts)
ValueError: invalid literal for int() with base 10: 'hordSym'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jwalls/music21/music21/harmony.py", line 1285, in chordSymbolFromChord
    cs = ChordSymbol(chordSymbolFigureFromChord(inChord))
  File "/Users/jwalls/music21/music21/harmony.py", line 1535, in __init__
    super().__init__(figure, **keywords)
  File "/Users/jwalls/music21/music21/harmony.py", line 208, in __init__
    self._parseFigure()
  File "/Users/jwalls/music21/music21/harmony.py", line 1860, in _parseFigure
    ) from ve
ValueError: Invalid chord abbreviation 'hordSymbolannotBeIdentified'; see music21.harmony.CHORD_TYPES for valid abbreviations or specify all alterations.

**Comment by mscuthbert** [comment]
i'm laughing, while agreeing -- this is a bug.  :-)
