### ISSUE TITLE
Meter documentation emits warnings on build

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#910]
FYI in case you didn't already know.

```
WARNING: autodoc: failed to import class 'MeterTerminalTuple' from module 'music21.meter'; the following exception was raised:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/util/inspect.py", line 401, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'music21.meter' has no attribute 'MeterTerminalTuple'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 107, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 320, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 2474, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/util/inspect.py", line 417, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: MeterTerminalTuple

WARNING: autodoc: failed to import function 'fractionSum' from module 'music21.meter'; the following exception was raised:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/util/inspect.py", line 401, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'music21.meter' has no attribute 'fractionSum'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 107, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 320, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 2474, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/util/inspect.py", line 417, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: fractionSum

WARNING: autodoc: failed to import function 'fractionToSlashMixed' from module 'music21.meter'; the following exception was raised:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/util/inspect.py", line 401, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'music21.meter' has no attribute 'fractionToSlashMixed'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 107, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 320, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 2474, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/util/inspect.py", line 417, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: fractionToSlashMixed

WARNING: autodoc: failed to import function 'proportionToFraction' from module 'music21.meter'; the following exception was raised:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/util/inspect.py", line 401, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'music21.meter' has no attribute 'proportionToFraction'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 107, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 320, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 2474, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/util/inspect.py", line 417, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: proportionToFraction

WARNING: autodoc: failed to import function 'slashCompoundToFraction' from module 'music21.meter'; the following exception was raised:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/util/inspect.py", line 401, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'music21.meter' has no attribute 'slashCompoundToFraction'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 107, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 320, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 2474, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/util/inspect.py", line 417, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: slashCompoundToFraction

WARNING: autodoc: failed to import function 'slashMixedToFraction' from module 'music21.meter'; the following exception was raised:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/util/inspect.py", line 401, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'music21.meter' has no attribute 'slashMixedToFraction'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 107, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 320, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 2474, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/util/inspect.py", line 417, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: slashMixedToFraction

WARNING: autodoc: failed to import function 'slashToTuple' from module 'music21.meter'; the following exception was raised:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/util/inspect.py", line 401, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'music21.meter' has no attribute 'slashToTuple'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 107, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 320, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 2474, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sphinx/util/inspect.py", line 417, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: slashToTuple
```

**Comment by jacobtylerwalls** [comment]
Nope -- all good, dirty directory somewhere. Closing.
