### ISSUE TITLE
Barlines in thawed streams raise AttributeErrors when accessing style

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#918]
**music21 version**

`7.0.1`

**Problem summary**
Unserializing a stream with a barline corrupts the `_style` attribute. Probably something to do with multiple inheritance and properties doing fancy footwork.

**Steps to reproduce**

```
>>> s = stream.Stream([bar.Barline()])
>>> data = converter.freezeStr(s, fmt='pickle')
>>> s2 = converter.thawStr(data)
>>> thawedBarline = s2.first()
>>> thawedBarline.hasStyleInformation
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jwalls/music21/music21/base.py", line 675, in hasStyleInformation
    return not (self._style is None)
AttributeError: _style
>>> '_style' in dir(thawedBarline)
True
>>> hasattr(thawedBarline, '_style')
False
```

**More information**
Encountered this loading a cached file from the corpus (writing a unit test for an upcoming unrelated patch).

I believe this is the only class to inherit from these two classes, each of which have slightly different implementations of `hasStyleInformation`.
https://github.com/cuthbertLab/music21/blob/747316f350319f0832d704c5d06a0c0bc2f07cbe/music21/bar.py#L96

- We could consolidate to just have one implementation of that method on `base.Music21Object` which catches AttributeError (which you would think would be unnecessary), which seemed to make my problems go away, but that could be masking something deeper. OK for now, I guess?

**Comment by jacobtylerwalls** [comment]
`git bisect` says it's a regression in 49f79cb43f3e1571a92a4dd1c744c9e1bb297785

**Comment by jacobtylerwalls** [comment]
Oh, that has to be it, there should never be a class inheriting from those two together:

https://github.com/cuthbertLab/music21/blob/e07d7ecb77f4dc0f9390709c058449156107810b/music21/style.py#L463-L469
