### ISSUE TITLE
"TypeError: 'NoneType' object is not iterable" while processing a MIDI file

### ISSUE THREAD

**Issue by mcory** [cuthbertLab/music21#94]
I'm a complete noob to python and music21, so this might be completely on me, but I figured I'd post just in case. FTR, I'm a pretty strong programmer in other languages (Java most explicitly), so feel free to ask for more details as needed.

I'm trying to use music21 to convert from MIDI files to MusicXML files, and the 3rd file I've tried crashes with the above error. The file itself is available at http://www.mutopiaproject.org/ftp/ChopinFF/O27/chopin-nocturne-8/chopin-nocturne-8.mid. The actual code I'm using is

```
s = music21.converter.parse(scorePath)
s.write('musicxml', '../data/out/musicxml/' + filename + ".xml")
```
(`scorePath` is the local path to the midi file)

It chokes on the converter.parse call, giving the following stack trace:

```
Traceback (most recent call last):
  File "./music21-test.py", line 13, in <module>
    s = music21.converter.parse(scorePath)
  File "/usr/local/lib/python2.7/dist-packages/music21-2.0.0-py2.7.egg/music21/converter/__init__.py", line 995, in parse
    return parseFile(value, number=number, format=m21Format, forceSource=forceSource)
  File "/usr/local/lib/python2.7/dist-packages/music21-2.0.0-py2.7.egg/music21/converter/__init__.py", line 893, in parseFile
    v.parseFile(fp, number=number, format=format, forceSource=forceSource)
  File "/usr/local/lib/python2.7/dist-packages/music21-2.0.0-py2.7.egg/music21/converter/__init__.py", line 484, in parseFile
    self.parseFileNoPickle(fp, number, format, forceSource)
  File "/usr/local/lib/python2.7/dist-packages/music21-2.0.0-py2.7.egg/music21/converter/__init__.py", line 425, in parseFileNoPickle
    self.subConverter.parseFile(fp, number=number)
  File "/usr/local/lib/python2.7/dist-packages/music21-2.0.0-py2.7.egg/music21/converter/subConverters.py", line 672, in parseFile
    midiTranslate.midiFilePathToStream(fp, self.stream)
  File "/usr/local/lib/python2.7/dist-packages/music21-2.0.0-py2.7.egg/music21/midi/translate.py", line 1927, in midiFilePathToStream
    return midiFileToStream(mf, inputM21)
  File "/usr/local/lib/python2.7/dist-packages/music21-2.0.0-py2.7.egg/music21/midi/translate.py", line 2063, in midiFileToStream
    ticksPerQuarter=mf.ticksPerQuarterNote, quantizePost=quantizePost, inputM21=s)
  File "/usr/local/lib/python2.7/dist-packages/music21-2.0.0-py2.7.egg/music21/midi/translate.py", line 1832, in midiTracksToStreams
    inputM21=streamPart)
  File "/usr/local/lib/python2.7/dist-packages/music21-2.0.0-py2.7.egg/music21/midi/translate.py", line 1614, in midiTrackToStream
    s.quantize([8, 3], processOffsets=True, processDurations=True, inPlace=True)
  File "/usr/local/lib/python2.7/dist-packages/music21-2.0.0-py2.7.egg/music21/stream/__init__.py", line 7915, in quantize
    unused_error, oNew, signedError = bestMatch(o, quarterLengthDivisors)
  File "/usr/local/lib/python2.7/dist-packages/music21-2.0.0-py2.7.egg/music21/stream/__init__.py", line 7891, in bestMatch
    match, error, signedError = common.nearestMultiple(target, (1.0/div))
TypeError: 'NoneType' object is not iterable
```
Again, if there's any other information you need, don't hesitate to ask - the script itself is pretty simple, just looping through the files in the directory where I've got the midi files, and there's two other MIDI files I've tried that seem to work fine.

Thanks!

**Comment by mscuthbert** [comment]
Not at all a NOOB question -- it appears that this MIDI file has some notes with negative duration (due to various backup tags) -- these notes now get converted to zero duration and parses properly.  See the latest github version (building now...)

**Comment by mcory** [comment]
Great - thanks Michael!
