### ISSUE TITLE
Set a floor of 0 for offset in measure when processing musicxml `<backup>`

### ISSUE THREAD

**Issue by jacobtylerwalls** [cuthbertLab/music21#971]
**music21 version**
dev

**Problem summary**
I encountered a musicxml file containing an extremely precise guitar transcription. As of today, we create unlinked durations when the quarter length doesn't match the type. That introduced some float rounding issues causing negative offsets. Accessing beats then crashes later.

The backup tag to start voice 2 is 4.0QL. We're at 3.9979, it seems, so we end up negative.

Need to use fractions for quarter lengths when creating these unlinked durations.

Missed case from #941

**Steps to reproduce**
[minimal.musicxml.zip](https://github.com/cuthbertLab/music21/files/6346248/minimal.musicxml.zip)

```
s = converter.parse('minimal.musicxml')
m = s.recurse().getElementsByClass(stream.Measure).first()
m.show('t', addEndTimes=True)
```

**Expected vs. actual behavior**
```
{0.0 - 0.0} <music21.layout.SystemLayout>
{0.0 - 0.0} <music21.layout.StaffLayout distance 65.15, staffNumber 1, staffSize None, staffLines None>
{0.0 - 3.9979} <music21.stream.Voice 1>
    {0.0 - 0.0312} <music21.note.Note E>
    {0.0312 - 0.125} <music21.chord.Chord E2 G#3 B3 E4>
    {0.125 - 0.5} <music21.chord.Chord E2 G#3 B3 E4>
    {0.5 - 1.0} <music21.chord.Chord E2 G#3 B3 E4>
    {1.0 - 2.0} <music21.chord.Chord E2 B2 E3 G#3 B3 E4>
    {2.0 - 2.0708} <music21.note.Note E>
    {2.0708 - 2.2146} <music21.chord.Chord E2 G#3 B3>
    {2.2146 - 2.2854} <music21.chord.Chord G#3 B3>
    {2.2854 - 2.5} <music21.chord.Chord B2 E3 G#3 B3>
    {2.5 - 2.5708} <music21.note.Note E>
    {2.5708 - 2.6417} <music21.chord.Chord E2 G#3 B3>
    {2.6417 - 2.7125} <music21.chord.Chord E2 G#3 B3 E4>
    {2.7125 - 2.9979} <music21.chord.Chord E2 G#3 B3 E4>
    {2.9979 - 3.2479} <music21.chord.Chord E2 G#3 B3 E4>
    {3.2479 - 3.2792} <music21.note.Rest rest>
    {3.2792 - 3.3729} <music21.chord.Chord B2 E3>
    {3.3729 - 3.4979} <music21.chord.Chord B2 E3>
    {3.4979 - 3.5292} <music21.note.Rest rest>
    {3.5292 - 3.6229} <music21.chord.Chord G#3 B3 E4>
    {3.6229 - 3.9979} <music21.chord.Chord G#3 B3 E4>
{0.0 - 3.9979} <music21.stream.Voice 2>
    {-0.0021 - 0.9979} <music21.chord.Chord B2 E3>
    {0.9979 - 1.9979} <music21.note.Rest rest>
    {1.9979 - 2.0604} <music21.note.Rest rest>
    {2.0604 - 2.2479} <music21.note.Note E>
    {2.2479 - 2.4979} <music21.note.Note E>
    {2.4979 - 3.9979} <music21.chord.Chord B2 E3>
{0.0 - 3.9979} <music21.stream.Voice 3>
    {-0.0021 - 1.9979} <music21.note.Rest rest>
    {1.9979 - 2.9979} <music21.chord.Chord B2 E3>
    {2.9979 - 3.2479} <music21.note.Rest rest>
    {3.2479 - 3.4979} <music21.chord.Chord G#3 B3 E4>
    {3.4979 - 3.9979} <music21.chord.Chord E2 B2 E3>
```

The negative offsets cause more trouble with the entire file:

```
for n in full.flat.notes:
  n.beat

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/jwalls/music21/music21/base.py", line 3404, in beat
    return ts.getBeatProportion(ts.getMeasureOffsetOrMeterModulusOffset(self))
  File "/Users/jwalls/music21/music21/meter/base.py", line 1916, in getBeatProportion
    beatIndex = self.beatSequence.offsetToIndex(qLenPos)
  File "/Users/jwalls/music21/music21/meter/core.py", line 1610, in offsetToIndex
    raise MeterException(
music21.exceptions21.MeterException: cannot access from qLenPos -1/480 where total duration is 4.0
```

**Comment by jacobtylerwalls** [comment]
Here are the durations:

```
>>> for e in m.recurse().notes:
...   print(e.duration)
... 
<music21.duration.Duration 0.03125>
<music21.duration.Duration 0.09375>
<music21.duration.Duration 0.375>
<music21.duration.Duration 0.5>
<music21.duration.Duration 1.0>
<music21.duration.Duration unlinked type:64th quarterLength:0.07083333333333333>
<music21.duration.Duration unlinked type:32nd quarterLength:0.14375>
<music21.duration.Duration unlinked type:64th quarterLength:0.07083333333333333>
<music21.duration.Duration unlinked type:32nd quarterLength:0.21458333333333332>
<music21.duration.Duration unlinked type:64th quarterLength:0.07083333333333333>
<music21.duration.Duration unlinked type:64th quarterLength:0.07083333333333333>
<music21.duration.Duration unlinked type:64th quarterLength:0.07083333333333333>
<music21.duration.Duration unlinked type:16th quarterLength:0.28541666666666665>
<music21.duration.Duration 0.25>
<music21.duration.Duration 0.09375>
<music21.duration.Duration 0.125>
<music21.duration.Duration 0.09375>
<music21.duration.Duration 0.375>
<music21.duration.Duration 1.0>
<music21.duration.Duration 0.1875>
<music21.duration.Duration 0.25>
<music21.duration.Duration 1.5>
<music21.duration.Duration 1.0>
<music21.duration.Duration 0.25>
<music21.duration.Duration 0.5>
```

**Comment by jacobtylerwalls** [comment]
Ah, the divisions here are 480 and the beat in question that's going haywire due to the septuplet, when I add the fractional divisions from the musicxml file, I get 479/480. So 0.9979 is correct for beat 2. Ouch! I don't know if this is common in commerical notation programs. MuseScore wrote the file. Probably just need a minimum of 0 for offset in measure when processing the backup tag.
